version: '3'
services:
  postgres:
    container_name: database
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - /postgres-data:/var/lib/postgresql/data
